apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-web-app
spec:
  replicas: 5
  selector:
    matchLabels:
      app: k8s-web-app
  template:
    metadata:
      labels:
        app: k8s-web-app
    spec:
      containers:
      - name: k8s-web-app
        image: itskumar/k8s-web-app
        resources:
          limits:
            memory: "128Mi"
            cpu: "250m"
        ports:
        - containerPort: 3000
